(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const S={credits:Number(localStorage.getItem('nvCredits')||1e7),sound:localStorage.getItem('nvSound')!=='off',game:null,slotId:'slots-classic'};
const RED=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
const ORDER=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
function fmt(n){n=Math.max(0,Math.floor(Number(n)||0));if(n>=1e9)return (n/1e9).toFixed(n>=1e10?0:2).replace(/\.0+$|(?<=\.\d)0$/,'')+'B';if(n>=1e6)return (n/1e6).toFixed(n>=1e7?0:2).replace(/\.0+$|(?<=\.\d)0$/,'')+'M';if(n>=1e3)return (n/1e3).toFixed(n>=1e4?0:1).replace(/\.0+$|(?<=\.\d)0$/,'')+'K';return n.toLocaleString()}
function chips(v){const s=String(v??'').trim().toUpperCase().replaceAll(',','');const m=s.match(/^(\d+(?:\.\d+)?)(K|M|B)?$/);if(!m)return NaN;return Math.floor(Number(m[1])*({K:1e3,M:1e6,B:1e9}[m[2]]||1))}
function setCredits(n){S.credits=Math.max(0,Math.floor(n));localStorage.setItem('nvCredits',S.credits);$('#balance').textContent=fmt(S.credits);$('#gameBalance').textContent=fmt(S.credits)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1900)}
function tone(f=440,d=.06,type='sine',gain=.025){if(!S.sound)return;try{const C=AudioContext||webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=f;g.gain.value=gain;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.stop(c.currentTime+d)}catch{}}
function win(){[560,700,880,1040].forEach((f,i)=>setTimeout(()=>tone(f,.09,'triangle',.035),i*55))}function lose(){tone(150,.15,'sawtooth',.025);setTimeout(()=>tone(100,.16,'sawtooth',.02),70)}
function home(){S.game=null;$$('.page').forEach(p=>p.classList.remove('active'));$('#homePage').classList.add('active');$('#crumb').textContent='LOBBY';$('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function section(id){home();setTimeout(()=>$('#'+id)?.scrollIntoView({behavior:'smooth',block:'start'}),40)}
function openGame(name){S.game=name;$$('.page').forEach(p=>p.classList.remove('active'));$('#gamePage').classList.add('active');$('#crumb').textContent=name.replace('slots-','').replaceAll('-',' ').toUpperCase();$('#gameCategory').textContent=name.startsWith('slots-')?'SLOT FLOOR':(['roulette','blackjack'].includes(name)?'TABLE FLOOR':'QUICK FLOOR');const names={roulette:'Neon Roulette',blackjack:'Blackjack 21','slots-classic':'Vault 777','slots-wild':'Wild Reactor','slots-crystal':'Crystal Rush','slots-neon':'Neon Fruits','slots-cosmic':'Cosmic 7s',plinko:'Neon Plinko',crash:'Vector Crash',mines:'Neon Mines',dice:'Six-Sided Dice',limbo:'Limbo'};$('#gameTitle').textContent=names[name];GAME[name]();window.scrollTo({top:0,behavior:'smooth'})}
function controlHTML(action){return `<div class="label">CHIP BET</div><div class="betline"><input id="betInput" value="100K"><button id="half">½</button><button id="dbl">2×</button></div><div class="quickline"><button data-q="10K">10K</button><button data-q="100K">100K</button><button data-q="1M">1M</button><button data-q="5M">5M</button></div><button class="main-action" id="mainAction">${action}</button>`}
function bindBet(){const i=$('#betInput');$$('[data-q]').forEach(b=>b.onclick=()=>i.value=b.dataset.q);$('#half')?.addEventListener('click',()=>i.value=fmt(Math.max(1000,Math.floor((chips(i.value)||1e5)/2))));$('#dbl')?.addEventListener('click',()=>i.value=fmt((chips(i.value)||1e5)*2))}
function getBet(){return chips($('#betInput')?.value||'')}
function mount(stage,controls){$('#mount').innerHTML=`<div class="game-shell"><div class="stage">${stage}</div><aside class="controls">${controls}</aside></div>`;bindBet();setCredits(S.credits)}
function roulette(){
 let choice={color:null,num:null};
 const pockets=ORDER.map((n,i)=>`<div class="pocket ${n===0?'green':RED.has(n)?'red':'black'}" style="transform:rotate(${i*360/37}deg)"><span>${n}</span></div>`).join('');
 mount(`<div class="roulette-stage"><div class="roulette-wrap"><div class="roulette-pointer"></div><div class="roulette-wheel" id="rouletteWheel">${pockets}<div class="roulette-center"><b>N</b></div></div></div><div class="roulette-result" id="rouletteResult">CHOOSE A NUMBER OR COLOR</div></div>`,
 `<div class="label">COLOR</div><div class="color-grid"><button data-color="RED" class="redc">RED<br><small>2×</small></button><button data-color="BLACK" class="blackc">BLACK<br><small>2×</small></button><button data-color="GREEN" class="greenc">0 / GREEN<br><small>14×</small></button></div><div class="label">NUMBER</div><div class="number-grid">${[...Array(37)].map((_,n)=>`<button data-num="${n}" class="${n===0?'green':RED.has(n)?'red':'black'}">${n}</button>`).join('')}</div>${controlHTML('SPIN WHEEL')}`);
 $$('[data-color]').forEach(b=>b.onclick=()=>{choice={color:b.dataset.color,num:null};$$('[data-color]').forEach(x=>x.classList.toggle('sel',x===b));$$('[data-num]').forEach(x=>x.classList.remove('sel'));tone(580,.04)});
 $$('[data-num]').forEach(b=>b.onclick=()=>{choice={color:null,num:+b.dataset.num};$$('[data-num]').forEach(x=>x.classList.toggle('sel',x===b));$$('[data-color]').forEach(x=>x.classList.remove('sel'));tone(580,.04)});
 $('#mainAction').onclick=()=>{const b=getBet();if(!b||b>S.credits)return toast(!b?'Enter a valid chip bet.':'Not enough chips.');if(!choice.color&&choice.num===null)return toast('Choose a number or color.');setCredits(S.credits-b);$('#mainAction').disabled=true;$('#rouletteResult').textContent='SPINNING…';const idx=Math.floor(Math.random()*37),result=ORDER[idx],color=result===0?'GREEN':RED.has(result)?'RED':'BLACK';const rotation=360*7-idx*(360/37);$('#rouletteWheel').style.transform=`rotate(${rotation}deg)`;let t=0;const tick=setInterval(()=>{tone(210+(t%8)*18,.022,'square',.008);t++},90);setTimeout(()=>{clearInterval(tick);let m=choice.num!==null?(choice.num===result?36:0):(choice.color===color?(color==='GREEN'?14:2):0);const payout=b*m;if(payout){setCredits(S.credits+payout);win()}else lose();$('#rouletteResult').textContent=`${result} • ${color} • ${payout?`WON ${fmt(payout)}`:'NO WIN'}`;$('#mainAction').disabled=false},3800)};
}

function blackjack(){
 const G={deck:[],dealer:[],hands:[],active:0,live:false};
 function fresh(){G.deck=[];for(const s of ['♠','♥','♦','♣'])for(let n=1;n<=13;n++)G.deck.push({s,n});for(let i=G.deck.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[G.deck[i],G.deck[j]]=[G.deck[j],G.deck[i]]}}
 const draw=()=>G.deck.pop();const val=h=>{let v=0,a=0;h.forEach(c=>{v+=c.n===1?11:Math.min(c.n,10);if(c.n===1)a++});while(v>21&&a){v-=10;a--}return v};
 const card=c=>{const r=c.n===1?'A':c.n===11?'J':c.n===12?'Q':c.n===13?'K':c.n;return `<div class="playing-card ${c.s==='♥'||c.s==='♦'?'red':''}"><span>${r} ${c.s}</span><span>${c.s}</span></div>`};
 function render(msg='READY'){const dealerHTML=G.dealer.map((c,i)=>G.live&&i===1?'<div class="playing-card back"><span>◆</span><span>◆</span></div>':card(c)).join('');const playerHTML=G.hands.map((h,i)=>`<div class="hand-pack" style="outline:${i===G.active&&G.live?'1px solid #69ff8a55':'0'};padding:4px;border-radius:12px"><div class="zone-head">HAND ${i+1} <b>${val(h.cards)}</b></div><div class="hand">${h.cards.map(card).join('')}</div></div>`).join('');mount(`<div class="bj-stage"><div class="zone"><div class="zone-head">DEALER <b>${G.live?'?':val(G.dealer)}</b></div><div class="hand">${dealerHTML}</div></div><div class="bj-message" id="bjMsg">${msg}</div><div class="zone"><div class="zone-head">PLAYER <b>${G.hands.map(h=>val(h.cards)).join(' / ')}</b></div><div class="hand">${playerHTML}</div></div></div>`,`${controlHTML('DEAL')}<div class="action-grid"><button class="small-act" id="hit">HIT</button><button class="small-act" id="stand">STAND</button><button class="small-act" id="double">DOUBLE</button><button class="small-act" id="split">SPLIT</button></div><div class="status"><b>RULES</b><br>Blackjack 3:2 • dealer stands on 17 • double after deal • one split.</div>`);$('#mainAction').onclick=start;$('#hit').onclick=hit;$('#stand').onclick=stand;$('#double').onclick=doubleDown;$('#split').onclick=split;['hit','stand','double','split'].forEach(id=>$('#'+id).disabled=!G.live);if(G.live&&G.hands[G.active]?.cards.length!==2)$('#double').disabled=true}
 function start(){const b=getBet();if(!b||b>S.credits)return toast(!b?'Enter a valid bet.':'Not enough chips.');setCredits(S.credits-b);fresh();G.dealer=[draw(),draw()];G.hands=[{cards:[draw(),draw()],bet:b,done:false,fromSplit:false}];G.active=0;G.live=true;render('YOUR TURN');tone(520,.08,'triangle');if(val(G.hands[0].cards)===21)setTimeout(stand,400)}
 function next(){const n=G.hands.findIndex((h,i)=>i>G.active&&!h.done);if(n>=0){G.active=n;render('NEXT HAND')}else finish()}
 function hit(){if(!G.live)return;const h=G.hands[G.active];h.cards.push(draw());tone(460,.05,'triangle');if(val(h.cards)>=21){h.done=true;next()}else render('YOUR TURN')}
 function stand(){if(!G.live)return;G.hands[G.active].done=true;next()}
 function doubleDown(){if(!G.live)return;const h=G.hands[G.active];if(h.cards.length!==2||S.credits<h.bet)return toast('Double needs an equal chip bet.');setCredits(S.credits-h.bet);h.bet*=2;h.cards.push(draw());h.done=true;tone(690,.08,'triangle');next()}
 function split(){if(!G.live||G.hands.length>1)return;const h=G.hands[0];if(h.cards.length!==2||h.cards[0].n!==h.cards[1].n||S.credits<h.bet)return toast('Split requires a matching pair and another equal bet.');setCredits(S.credits-h.bet);const second={cards:[h.cards.pop(),draw()],bet:h.bet,done:false,fromSplit:true};h.cards.push(draw());G.hands.push(second);render('SPLIT • HAND 1');tone(780,.1,'triangle')}
 function finish(){G.live=false;while(val(G.dealer)<17)G.dealer.push(draw());const d=val(G.dealer);let payout=0,msg=[];G.hands.forEach(h=>{const p=val(h.cards),nat=h.cards.length===2&&p===21;let r=0;if(p>21)msg.push('BUST');else if(d>21||p>d){r=nat&&!h.fromSplit?h.bet*2.5:h.bet*2;msg.push('WIN')}else if(p===d){r=h.bet;msg.push('PUSH')}else msg.push('DEALER WINS');payout+=r});if(payout)setCredits(S.credits+payout);render(msg.join(' • '));payout?win():lose()}
 render()
}
const ROOMS={
'slots-classic':{name:'Vault 777',symbols:['7','★','◆','BAR','🍒'],pay:[['7 7 7',25],['★ ★ ★',10],['◆ ◆ ◆',7],['🍒 🍒 🍒',4]],bonus:'JACKPOT WHEEL',bonusM:8},
'slots-wild':{name:'Wild Reactor',symbols:['W','⚡','🔥','☢','7'],pay:[['W W W',30],['⚡ ⚡ ⚡',12],['🔥 🔥 🔥',8],['7 7 7',5]],bonus:'REACTOR CHARGE',bonusM:10},
'slots-crystal':{name:'Crystal Rush',symbols:['💎','🔷','💠','7','✦'],pay:[['💎 💎 💎',50],['🔷 🔷 🔷',15],['💠 💠 💠',8],['✦ ✦ ✦',4]],bonus:'GEM CASCADE',bonusM:12},
'slots-neon':{name:'Neon Fruits',symbols:['🍒','🍋','🍊','🍉','7'],pay:[['🍒 🍒 🍒',8],['🍉 🍉 🍉',6],['🍊 🍊 🍊',4],['7 7 7',18]],bonus:'FRUIT BURST',bonusM:7},
'slots-cosmic':{name:'Cosmic 7s',symbols:['🪐','🌙','☄','✦','7'],pay:[['7 7 7',35],['✦ ✦ ✦',14],['☄ ☄ ☄',9],['🪐 🪐 🪐',6]],bonus:'STAR BURST',bonusM:15}
};
function slots(id){const r=ROOMS[id];S.slotId=id;mount(`<div class="slot-stage"><div class="slot-top"><div><p class="eyebrow">SLOT ROOM</p><h3>${r.name}</h3></div><small>${r.bonus}</small></div><div class="slot-tabs">${Object.entries(ROOMS).map(([k,v])=>`<button class="slot-tab ${k===id?'active':''}" data-room="${k}">${v.name}</button>`).join('')}</div><div class="reel-window"><div class="reel" id="s1">${r.symbols[0]}</div><div class="reel" id="s2">${r.symbols[1]}</div><div class="reel" id="s3">${r.symbols[2]}</div><div class="reel-line"></div></div><div class="slot-status" id="slotStatus">READY</div><div class="paytable">${r.pay.map(p=>`<div class="pay"><span>${p[0]}</span><b>${p[1]}×</b></div>`).join('')}</div></div>`,`${controlHTML('SPIN')}<div class="bonus-line"><div class="title"><span>BONUS TESTS</span><span>GUARANTEED</span></div><button data-bonus="normal">FORCE ${r.bonus}</button><button data-bonus="mega">FORCE 50× MEGA</button><button data-bonus="handpay">FORCE HANDPAY</button></div><div class="status"><b>ROOM PAYOUTS</b><br>Exact triples pay the listed multiplier. Any pair pays 1.5×.</div>`);$$('[data-room]').forEach(b=>b.onclick=()=>openGame(b.dataset.room));$$('[data-bonus]').forEach(b=>b.onclick=()=>forceSlotBonus(b.dataset.bonus));$('#mainAction').onclick=()=>spinSlots()}
async function spinSlots(){if(S.slotBusy)return;const b=getBet(),r=ROOMS[S.slotId];if(!b||b>S.credits)return toast(!b?'Enter a valid bet.':'Not enough chips.');S.slotBusy=true;setCredits(S.credits-b);$('#mainAction').disabled=true;const els=[$('#s1'),$('#s2'),$('#s3')];els.forEach(e=>e.classList.add('spin'));$('#slotStatus').textContent='SPINNING…';const timer=setInterval(()=>{els.forEach(e=>e.textContent=r.symbols[Math.floor(Math.random()*r.symbols.length)]);tone(170+Math.random()*70,.02,'square',.006)},70);await new Promise(res=>setTimeout(res,950));clearInterval(timer);const out=[0,1,2].map(()=>r.symbols[Math.floor(Math.random()*r.symbols.length)]);for(let i=0;i<3;i++){await new Promise(res=>setTimeout(res,180));els[i].classList.remove('spin');els[i].textContent=out[i];tone(420+i*100,.07,'triangle',.03)}let m=0;if(out[0]===out[1]&&out[1]===out[2])m=r.pay.find(p=>p[0].startsWith(out[0]+' '))?.[1]||3;else if(new Set(out).size===2)m=1.5;const p=Math.floor(b*m);if(p){setCredits(S.credits+p);win()}else lose();$('#slotStatus').textContent=p?`${out.join(' ')} • WON ${fmt(p)}`:`${out.join(' ')} • NO WIN`;S.slotBusy=false;$('#mainAction').disabled=false}
function forceSlotBonus(kind){const b=getBet()||100000,r=ROOMS[S.slotId],m=kind==='mega'?50:r.bonusM;if(kind==='handpay'){const p=Math.max(1e7,b*25);setCredits(S.credits+p);$('#slotStatus').textContent='HANDPAY TEST • +'+fmt(p);win();return}setCredits(S.credits+b*m);$('#slotStatus').textContent=`${r.bonus} • +${fmt(b*m)}`;win()}

function plinko(){let risk='low',busy=false;const MAP={low:[.5,.7,1,1.2,1.6,1.2,1,.7,.5],medium:[.2,.5,1.5,2.5,5,2.5,1.5,.5,.2],high:[.1,.25,.6,2,8,2,.6,.25,.1]};function render(){let pegs='';for(let r=0;r<10;r++){const c=r+3;for(let i=0;i<c;i++)pegs+=`<i class="plinko-peg" style="left:${(i+.5)*100/c}%;top:${8+r*7.7}%"></i>`}mount(`<div class="plinko-stage"><div class="plinko-top"><div><p class="eyebrow">DROP MACHINE</p><b style="font:700 22px Space Grotesk">Neon Plinko</b></div><div class="risk-bar">${Object.keys(MAP).map(x=>`<button data-risk="${x}" class="${x===risk?'active':''}">${x.toUpperCase()}</button>`).join('')}</div></div><div id="plinkoBoard" class="plinko-board"><div>${pegs}</div><div id="plinkoBall" class="plinko-ball"></div><div class="bins">${MAP[risk].map((m,i)=>`<div class="bin" data-bin="${i}">${m}×</div>`).join('')}</div></div></div>`,`${controlHTML('DROP CHIP')}<div class="status" id="riskStatus"><b>${risk.toUpperCase()} RISK</b><br>${MAP[risk].map(x=>x+'×').join(' • ')}</div>`);$$('[data-risk]').forEach(b=>b.onclick=()=>{if(busy)return;risk=b.dataset.risk;render();tone(610,.05,'triangle')});$('#mainAction').onclick=drop}
function drop(){if(busy)return;const b=getBet();if(!b||b>S.credits)return toast(!b?'Enter a valid bet.':'Not enough chips.');busy=true;setCredits(S.credits-b);$('#mainAction').disabled=true;const target=Math.floor(Math.random()*9),ball=$('#plinkoBall');ball.style.opacity=1;const pts=[{x:50,y:4}],n=12;let x=50;for(let i=1;i<n;i++){x=Math.max(12,Math.min(88,x+(Math.random()>.5?4.2:-4.2)));pts.push({x,y:4+i*6.5})}pts.push({x:10+target*10,y:88});let i=0;const move=()=>{if(i>=pts.length-1){const p=Math.floor(b*MAP[risk][target]);setCredits(S.credits+p);$(`[data-bin="${target}"]`)?.classList.add('hit');setTimeout(()=>{$(`[data-bin="${target}"]`)?.classList.remove('hit')},600);p>=b?win():lose();busy=false;$('#mainAction').disabled=false;return}const a=pts[i],c=pts[i+1],st=performance.now();const frame=now=>{const t=Math.min(1,(now-st)/140),e=t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;ball.style.left=(a.x+(c.x-a.x)*e)+'%';ball.style.top=(a.y+(c.y-a.y)*e)+'%';if(t<1)requestAnimationFrame(frame);else{i++;tone(280+i*17,.025,'triangle',.012);move()}};requestAnimationFrame(frame)};move()}
render()}
function crash(){let live=false,raf=0,current=1;mount(`<div class="crash-stage"><div class="crash-mult" id="crashMult">1.00×</div><svg class="crash-svg" viewBox="0 0 600 300"><polyline points="0,275 80,258 135,265 205,225 270,235 350,170 425,188 500,90 600,22"></polyline></svg></div>`,`${controlHTML('START ROUND')}<div id="cashWrap"></div><div id="crashStatus" class="status"><b>READY</b><br>Start a round, then the cash-out button is live.</div>`);$('#mainAction').onclick=()=>{if(live)return;const b=getBet();if(!b||b>S.credits)return toast(!b?'Enter a valid bet.':'Not enough chips.');setCredits(S.credits-b);live=true;current=1;const point=1.08+Math.random()*7.8,start=performance.now();$('#mainAction').disabled=true;$('#cashWrap').innerHTML='<button id="cashout" class="main-action cashout">CASH OUT 1.00×</button>';$('#cashout').onclick=()=>{if(!live)return;const p=Math.floor(b*current);setCredits(S.credits+p);$('#crashStatus').innerHTML=`<b>PAID ${fmt(p)}</b><br>Cashed out at ${current.toFixed(2)}×.`;win();live=false;cancelAnimationFrame(raf);$('#mainAction').disabled=false;$('#cashWrap').innerHTML=''};const frame=now=>{const t=(now-start)/1000;current=1+t*.55+t*t*.15;$('#crashMult').textContent=current.toFixed(2)+'×';$('#cashout').textContent=`CASH OUT ${current.toFixed(2)}×`;if(current>=point){$('#crashMult').textContent=point.toFixed(2)+'×';$('#crashMult').classList.add('crashed');$('#crashStatus').innerHTML=`<b>CRASHED</b><br>Round ended at ${point.toFixed(2)}×.`;lose();live=false;$('#mainAction').disabled=false;$('#cashWrap').innerHTML='';return}raf=requestAnimationFrame(frame)};raf=requestAnimationFrame(frame)}}

function mines(){let live=false,mineSet=new Set(),b=0,opened=0,reward=1;function render(){const c=Array.from({length:25},(_,i)=>`<button class="mine-cell" data-cell="${i}">?</button>`).join('');mount(`<div class="mines-stage"><div><div class="mine-grid" id="mineGrid">${c}</div><div id="mineStatus" style="text-align:center;margin-top:18px;color:#718176;font-size:9px">START A ROUND</div></div></div>`,`${controlHTML('START ROUND')}<button class="sub-action" id="resetMines">RESET BOARD</button><div class="status"><b id="mineReward">REWARD 1.00×</b><br>Every safe tile raises the reward.</div>`);$('#mainAction').onclick=start;$('#resetMines').onclick=()=>{live=false;mineSet=new Set();b=0;opened=0;reward=1;render()};$$('[data-cell]').forEach(x=>x.onclick=()=>reveal(+x.dataset.cell))}
function start(){const x=getBet();if(!x||x>S.credits)return toast(!x?'Enter a valid bet.':'Not enough chips.');b=x;setCredits(S.credits-b);mineSet=new Set();while(mineSet.size<5)mineSet.add(Math.floor(Math.random()*25));opened=0;reward=1;live=true;$$('.mine-cell').forEach(c=>{c.className='mine-cell';c.textContent='?';c.disabled=false});$('#mineStatus').textContent='ROUND LIVE • PICK A TILE';$('#mineReward').textContent='REWARD 1.00×';tone(420,.06,'triangle')}
function reveal(i){if(!live)return;const c=$(`[data-cell="${i}"]`);if(c.classList.contains('revealed'))return;c.classList.add('revealed');if(mineSet.has(i)){c.classList.add('mine');c.textContent='✦';live=false;$$('[data-cell]').forEach((x,n)=>{if(mineSet.has(n)){x.classList.add('revealed','mine');x.textContent='✦'}});$('#mineStatus').textContent='MINE HIT • ROUND OVER';lose();return}opened++;reward=1+opened*.35;c.classList.add('safe');c.textContent='◆';$('#mineReward').textContent=`REWARD ${reward.toFixed(2)}×`;$('#mineStatus').textContent=`SAFE • ${opened}/20`;tone(600+opened*22,.05,'triangle',.03);if(opened===20){const p=Math.floor(b*reward);setCredits(S.credits+p);live=false;$('#mineStatus').textContent=`BOARD CLEARED • +${fmt(p)}`;win()}}
render()}

function dice(){let pick='high',face=6;mount(`<div class="dice-stage"><div class="die-wrap"><div id="die" class="die">1</div><div class="dice-note">ACTUAL SIX-SIDED DIE</div></div></div>`,`${controlHTML('ROLL DICE')}<div class="label" style="margin-top:14px">CHOOSE OUTCOME</div><div class="choice-grid"><button class="choice active" data-pick="high">HIGH<br>4–6</button><button class="choice" data-pick="low">LOW<br>1–3</button><button class="choice" data-pick="exact">EXACT<br>FACE</button></div><div class="choice-grid" id="faces" style="display:none;margin-top:6px">${[1,2,3,4,5,6].map(n=>`<button class="choice" data-face="${n}">${n}</button>`).join('')}</div><div class="status"><b>REAL D6</b><br>High and low pay 1.9×. Exact face pays 5×.</div>`);$$('[data-pick]').forEach(x=>x.onclick=()=>{pick=x.dataset.pick;$$('[data-pick]').forEach(b=>b.classList.toggle('active',b===x));$('#faces').style.display=pick==='exact'?'grid':'none';tone(500,.04)});$$('[data-face]').forEach(x=>x.onclick=()=>{face=+x.dataset.face;$$('[data-face]').forEach(b=>b.classList.toggle('active',b===x));tone(520,.04)});$('#mainAction').onclick=()=>{const b=getBet();if(!b||b>S.credits)return toast(!b?'Enter a valid bet.':'Not enough chips.');setCredits(S.credits-b);const n=1+Math.floor(Math.random()*6),d=$('#die');d.classList.remove('roll');void d.offsetWidth;d.classList.add('roll');const interval=setInterval(()=>{d.textContent=1+Math.floor(Math.random()*6)},90);setTimeout(()=>{clearInterval(interval);d.textContent=n;const ok=pick==='high'?n>=4:pick==='low'?n<=3:n===face;const p=ok?Math.floor(b*(pick==='exact'?5:1.9)):0;if(p){setCredits(S.credits+p);win()}else lose()},820)}}

function limbo(){let live=false,raf=0,current=1,b=0;mount(`<div class="limbo-stage"><div><div class="limbo-mult" id="limboMult">1.00×</div><div class="limbo-target" id="limboTarget">TARGET 2.00×</div></div></div>`,`${controlHTML('START LIMBO')}<div class="label" style="margin-top:14px">TARGET</div><div class="betline"><input id="targetInput" value="2.00"></div><div id="limboCash"></div><div class="status" id="limboStatus"><b>READY</b><br>The multiplier rises live. Cash out any time before the crash.</div>`);$('#targetInput').oninput=()=>$('#limboTarget').textContent='TARGET '+Math.max(1.01,Number($('#targetInput').value)||1.01).toFixed(2)+'×';$('#mainAction').onclick=()=>{if(live)return;const target=Math.max(1.01,Number($('#targetInput').value)||1.01);b=getBet();if(!b||b>S.credits)return toast(!b?'Enter a valid bet.':'Not enough chips.');setCredits(S.credits-b);current=1;live=true;const crash=1.08+Math.pow(Math.random(),1.7)*9,start=performance.now();$('#mainAction').disabled=true;$('#limboCash').innerHTML='<button id="limboCashout" class="main-action cashout">CASH OUT 1.00×</button>';$('#limboCashout').onclick=()=>{if(!live)return;const p=Math.floor(b*current);setCredits(S.credits+p);$('#limboStatus').innerHTML=`<b>PAID ${fmt(p)}</b><br>Cashed at ${current.toFixed(2)}×.`;win();live=false;cancelAnimationFrame(raf);$('#mainAction').disabled=false;$('#limboCash').innerHTML=''};const frame=now=>{const t=(now-start)/1000;current=1+t*.48+t*t*.1;$('#limboMult').textContent=current.toFixed(2)+'×';$('#limboCashout').textContent=`CASH OUT ${current.toFixed(2)}×`;if(current>=crash){$('#limboMult').textContent=crash.toFixed(2)+'×';$('#limboStatus').innerHTML=`<b>CRASH ${crash.toFixed(2)}×</b><br>Target was ${target.toFixed(2)}×.`;lose();live=false;$('#mainAction').disabled=false;$('#limboCash').innerHTML='';return}raf=requestAnimationFrame(frame)};raf=requestAnimationFrame(frame)}}

const GAME={roulette,blackjack,plinko,crash,mines,dice,limbo,'slots-classic':()=>slots('slots-classic'),'slots-wild':()=>slots('slots-wild'),'slots-crystal':()=>slots('slots-crystal'),'slots-neon':()=>slots('slots-neon'),'slots-cosmic':()=>slots('slots-cosmic')};
function goHome(){home()}
function bindGlobal(){ $$('[data-game]').forEach(x=>x.addEventListener('click',()=>openGame(x.dataset.game))); $$('[data-home]').forEach(x=>x.addEventListener('click',home)); $$('[data-section]').forEach(x=>x.addEventListener('click',()=>section(x.dataset.section))); $('#plusChip').onclick=()=>{setCredits(S.credits+1e6);toast('+1M DEMO CHIPS')}; $('#devBtn').onclick=()=>$('#devModal').classList.add('open'); $('#closeDev').onclick=()=>$('#devModal').classList.remove('open'); $('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open'); $('#soundBtn').onclick=()=>{S.sound=!S.sound;localStorage.setItem('nvSound',S.sound?'on':'off');$('#soundBtn').innerHTML=S.sound?'🔊 Sound <small>ON</small>':'🔇 Sound <small>OFF</small>';tone(650)}; $$('[data-add]').forEach(x=>x.onclick=()=>{const n=chips(x.dataset.add);setCredits(S.credits+n);toast('+'+x.dataset.add+' DEMO CHIPS')}); $('#reset').onclick=()=>{setCredits(1e7);toast('RESET TO 10M')}; }
bindGlobal();setCredits(S.credits);
})();
