const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let credits=Number(localStorage.getItem('neonCredits')||10000000),soundOn=localStorage.getItem('neonSound')!=='off',audioCtx;
const fmt=n=>{const a=Math.abs(n);if(a>=1e9)return (n/1e9).toFixed(a>=1e10?0:2).replace(/\.?(0+)$/,'')+'B';if(a>=1e6)return (n/1e6).toFixed(a>=1e7?0:2).replace(/\.?(0+)$/,'')+'M';if(a>=1e3)return (n/1e3).toFixed(a>=1e4?0:1).replace(/\.?(0+)$/,'')+'K';return Math.round(n).toLocaleString()};
const parseAmount=v=>{const s=String(v).trim().toUpperCase().replace(/[$,\s]/g,'');const m=s.match(/^(\d*\.?\d+)([KMB])?$/);if(!m)return NaN;return Math.floor(Number(m[1])*({K:1e3,M:1e6,B:1e9}[m[2]]||1))};
function setCredits(n){credits=Math.max(0,Math.floor(n));localStorage.setItem('neonCredits',credits);$('#credits').textContent=fmt(credits)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function beep(freq=440,d=.08,type='sine',gain=.04){if(!soundOn)return;audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.stop(audioCtx.currentTime+d)}
function winSound(){[523,659,784,1047,1318].forEach((f,i)=>setTimeout(()=>beep(f,.13,'triangle',.055),i*75))}function loseSound(){beep(180,.2,'sawtooth',.035);setTimeout(()=>beep(120,.22,'sawtooth',.03),120)}
setCredits(credits);$('#soundBtn').textContent=soundOn?'🔊':'🔇';$('#soundBtn').onclick=()=>{soundOn=!soundOn;localStorage.setItem('neonSound',soundOn?'on':'off');$('#soundBtn').textContent=soundOn?'🔊':'🔇';beep(660)};
$$('[data-go]').forEach(b=>b.onclick=()=>{const id=b.dataset.go;$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');scrollTo({top:0,behavior:'smooth'});beep(420,.05,'triangle')});
$('#devBtn').onclick=()=>$('#devModal').classList.remove('hidden');$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$$('[data-addcredits]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.addcredits);setCredits(credits+n);toast('Added '+fmt(n)+' chips');beep(900)});$('#resetCredits').onclick=()=>{setCredits(10000000);toast('Reset to 10M chips')};
const canvas=$('#bg'),ctx=canvas.getContext('2d');let pts=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);pts=Array.from({length:38},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.2+.2,s:Math.random()*.18+.04}))}function drawBg(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#58ff7855';pts.forEach(p=>{p.y-=p.s;if(p.y<0)p.y=innerHeight;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(drawBg)}resize();addEventListener('resize',resize);drawBg();

/* ROULETTE — the wheel, pocket labels and result all use the same wheelOrder. */
const wheelOrder=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
const redNums=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);let rBet=null,rSpinning=false,rRotation=0;
const wheelNumbers=$('#wheelNumbers');wheelOrder.forEach((n,i)=>{const s=document.createElement('span');const a=i*360/wheelOrder.length;s.textContent=n;s.dataset.n=n;s.style.setProperty('--a',`${a}deg`);s.style.color=n===0?'#71ff8b':redNums.has(n)?'#ff7183':'#f2f6f3';wheelNumbers.appendChild(s)});
for(let n=0;n<=36;n++){const b=document.createElement('button');b.textContent=n;b.dataset.rbet=n;b.className=n===0?'zero':redNums.has(n)?'red':'black';$('#rouletteTable').appendChild(b)}
function selectRBet(v,el){rBet=String(v);$$('[data-rbet]').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');$('#rouletteSelected').innerHTML=`<b>${/^\d+$/.test(rBet)?'NUMBER '+rBet:rBet.toUpperCase()}</b> selected`;beep(520,.05,'triangle')}
$('#rouletteTable').onclick=e=>{const b=e.target.closest('[data-rbet]');if(b)selectRBet(b.dataset.rbet,b)};$$('.outside-bets [data-rbet]').forEach(b=>b.onclick=()=>selectRBet(b.dataset.rbet,b));$$('[data-rquick]').forEach(b=>b.onclick=()=>{$('#rouletteAmount').value=fmt(Number(b.dataset.rquick));$('#rouletteAmount').dispatchEvent(new Event('input'))});
$('#rouletteAmount').oninput=()=>{const n=parseAmount($('#rouletteAmount').value);$('#rouletteBetTotal').textContent=Number.isFinite(n)?fmt(n):'—'};$('#rouletteAmount').dispatchEvent(new Event('input'));
function rouletteWin(bet,num){if(/^\d+$/.test(bet))return Number(bet)===num?36:0;if(num===0)return 0;if(bet==='red')return redNums.has(num)?2:0;if(bet==='black')return !redNums.has(num)?2:0;if(bet==='even')return num%2===0?2:0;if(bet==='odd')return num%2?2:0;if(bet==='low')return num<=18?2:0;if(bet==='high')return num>=19?2:0;return 0}
function spinRoulette(){if(rSpinning)return;if(rBet===null)return toast('Choose a number or color first.');const amt=parseAmount($('#rouletteAmount').value);if(!amt||amt<1)return toast('Enter a chip amount like 100K or 1M.');if(amt>credits)return toast('Not enough chips.');rSpinning=true;setCredits(credits-amt);$('#spinRoulette').disabled=true;$('#rouletteResult').textContent='SPINNING…';const result=wheelOrder[Math.floor(Math.random()*wheelOrder.length)],idx=wheelOrder.indexOf(result),sector=360/wheelOrder.length;const target=((idx*sector)+sector/2);const turns=5;const newRotation=rRotation+turns*360+(360-target-(rRotation%360)+360)%360;rRotation=newRotation;$('#rouletteWheel').style.transition='transform 4.5s cubic-bezier(.12,.78,.09,1)';$('#rouletteWheel').style.transform=`rotate(${newRotation}deg)`;let ticks=0;const timer=setInterval(()=>{beep(250+(ticks%7)*24,.024,'square',.01);ticks++},95);setTimeout(()=>{clearInterval(timer);const mult=rouletteWin(rBet,result),color=result===0?'GREEN':redNums.has(result)?'RED':'BLACK',payout=amt*mult;setCredits(credits+payout);$('#rouletteResult').textContent=payout?`${result} • ${color} • WON ${fmt(payout)}`:`${result} • ${color} • NO WIN`;payout?winSound():loseSound();$('#spinRoulette').disabled=false;rSpinning=false},4550)}
$('#spinRoulette').onclick=spinRoulette;

/* BLACKJACK */
const suits=['♠','♥','♦','♣'],ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];let deck=[],dealer=[],hands=[],activeHand=0,bjRunning=false,dealerHidden=true;
function newDeck(){deck=[];for(const s of suits)for(const r of ranks)deck.push({r,s});for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}}
function val(hand){let v=0,a=0;hand.forEach(c=>{if(c.r==='A'){v+=11;a++}else v+=['J','Q','K'].includes(c.r)?10:Number(c.r)});while(v>21&&a){v-=10;a--}return v}
function cardEl(c,back=false){const d=document.createElement('div');d.className='playing-card'+(back?' back':(['♥','♦'].includes(c.s)?' red-suit':''));if(!back)d.innerHTML=`${c.r}<span class="suit">${c.s}</span>`;return d}
function renderBJ(){const dh=$('#dealerHand');dh.innerHTML='';dealer.forEach((c,i)=>dh.appendChild(cardEl(c,dealerHidden&&i===1)));$('#dealerScore').textContent=dealer.length?(dealerHidden?val([dealer[0]]):val(dealer)):'';const ph=$('#playerHands');ph.innerHTML='';hands.forEach((h,i)=>{const w=document.createElement('div');w.className='split-hand '+(i===activeHand&&bjRunning?'active-hand':'');h.cards.forEach(c=>w.appendChild(cardEl(c)));ph.appendChild(w)});$('#playerScore').textContent=hands.length===1?val(hands[0]?.cards||[]):hands.map(h=>val(h.cards)).join(' / ');const h=hands[activeHand];$('#bjHit').disabled=!bjRunning||!h;$('#bjStand').disabled=!bjRunning||!h;$('#bjDouble').disabled=!bjRunning||!h||h.cards.length!==2||credits<h.bet;$('#bjSplit').disabled=!bjRunning||!h||h.cards.length!==2||h.cards[0].r!==h.cards[1].r||credits<h.bet||hands.length>=4;$('#bjDeal').disabled=bjRunning;$('#bjChipVisual').textContent=$('#bjAmount').value||'—'}
function bjNextOrDealer(){if(activeHand<hands.length-1){activeHand++;renderBJ();$('#bjStatus').textContent='Playing hand '+(activeHand+1);return}dealerTurn()}
function finishBJ(){dealerHidden=false;const dv=val(dealer);let totalReturn=0,msg=[];hands.forEach(h=>{const pv=val(h.cards),nat=h.cards.length===2&&pv===21&&!h.fromSplit,dnat=dealer.length===2&&dv===21;let ret=0;if(pv>21)msg.push('BUST');else if(dv>21||pv>dv){ret=h.bet*(nat&&!dnat?2.5:2);msg.push('WIN '+fmt(ret))}else if(pv===dv){ret=h.bet;msg.push('PUSH')}else msg.push('DEALER WINS');totalReturn+=ret});if(totalReturn)setCredits(credits+totalReturn);$('#bjStatus').textContent=msg.join(' • ');totalReturn>hands.reduce((s,h)=>s+h.bet,0)?winSound():loseSound();bjRunning=false;renderBJ()}
function dealerTurn(){dealerHidden=false;renderBJ();$('#bjStatus').textContent='Dealer playing…';const iv=setInterval(()=>{if(val(dealer)<17){dealer.push(deck.pop());beep(380,.06,'triangle');renderBJ()}else{clearInterval(iv);setTimeout(finishBJ,350)}},500)}
$$('[data-bjquick]').forEach(b=>b.onclick=()=>{$('#bjAmount').value=fmt(Number(b.dataset.bjquick));$('#bjAmount').dispatchEvent(new Event('input'))});$('#bjAmount').oninput=()=>{$('#bjBetDisplay').textContent=$('#bjAmount').value||'—';$('#bjChipVisual').textContent=$('#bjAmount').value||'—'};
$('#bjDeal').onclick=()=>{const amt=parseAmount($('#bjAmount').value);if(!amt||amt<1)return toast('Enter a valid chip bet.');if(amt>credits)return toast('Not enough chips.');setCredits(credits-amt);newDeck();dealer=[deck.pop(),deck.pop()];hands=[{cards:[deck.pop(),deck.pop()],bet:amt,fromSplit:false}];activeHand=0;dealerHidden=true;bjRunning=true;$('#bjStatus').textContent='Your move.';renderBJ();beep(520);if(val(hands[0].cards)===21)setTimeout(dealerTurn,650)};
$('#bjHit').onclick=()=>{const h=hands[activeHand];h.cards.push(deck.pop());beep(500,.05,'triangle');renderBJ();if(val(h.cards)>=21)setTimeout(bjNextOrDealer,350)};$('#bjStand').onclick=bjNextOrDealer;$('#bjDouble').onclick=()=>{const h=hands[activeHand];if(!h||credits<h.bet)return;setCredits(credits-h.bet);h.bet*=2;h.cards.push(deck.pop());beep(700);renderBJ();setTimeout(bjNextOrDealer,400)};$('#bjSplit').onclick=()=>{const h=hands[activeHand];if(!h||credits<h.bet)return;setCredits(credits-h.bet);const c2=h.cards.pop();h.fromSplit=true;h.cards.push(deck.pop());hands.splice(activeHand+1,0,{cards:[c2,deck.pop()],bet:h.bet,fromSplit:true});beep(800);renderBJ()};renderBJ();

/* SLOTS */
const cabinets={pulse:{title:'PULSE',title2:'JACKPOT',badge:'7 / STAR / DIAMOND',symbols:['7','★','◆','🍒','BAR'],weights:['7','★','◆','🍒','BAR','◆','🍒','BAR','🍒','◆','BAR'],pays:[['7 7 7','25×'],['★ ★ ★','12×'],['◆ ◆ ◆','8×'],['🍒 🍒 🍒','5×'],['ANY EXACT PAIR','1.5×']],bonus:'PINBALL BONUS',desc:'Animated neon pinball with 2×, 5×, 10×, 25× and 50× bonus slots.'},wild:{title:'WILD',title2:'REACTOR',badge:'WILD / 7 / GEM / BAR',symbols:['W','7','💎','BAR','⚡'],weights:['W','W','7','7','💎','BAR','⚡','W','7','💎'],pays:[['W W W','30×'],['7 7 7','20×'],['💎 💎 💎','15×'],['⚡ ⚡ ⚡','10×'],['ANY EXACT PAIR','2×']],bonus:'REACTOR BOOST',desc:'A guaranteed energy boost bonus with a 5×–40× reactor multiplier.'},crystal:{title:'CRYSTAL',title2:'VAULT',badge:'GEM / STAR / 7 / ORB',symbols:['💎','★','7','🔷','🍒'],weights:['💎','💎','★','★','7','🔷','🍒','💎','★','7'],pays:[['💎 💎 💎','40×'],['★ ★ ★','18×'],['7 7 7','12×'],['🔷 🔷 🔷','9×'],['ANY EXACT PAIR','2×']],bonus:'VAULT DROP',desc:'Crystal bonus drops a guaranteed 3×–50× multiplier into your chip balance.'}};
let cabinet='pulse',slotBusy=false,slotBet=100000;
function randSym(){const c=cabinets[cabinet];return c.weights[Math.floor(Math.random()*c.weights.length)]}function slotMult(a){const c=cabinets[cabinet];const all=a.every(x=>x===a[0]);if(all){const row=c.pays.find(p=>p[0].split(' ').every(x=>x===a[0]));return row?Number(row[1].replace('×','')):5}if(a.filter(x=>x===a[0]).length===2||a.filter(x=>x===a[1]).length===2||a.filter(x=>x===a[2]).length===2)return 1.5;return 0}
function renderCabinet(){const c=cabinets[cabinet];$('#slotTitle').textContent=c.title;$('#slotTitle2').textContent=c.title2;$('#cabinetBadge').textContent=c.badge;$('#bonusTitle').textContent=c.title+' payouts';$('#bonusName').textContent=c.bonus;$('#bonusDescription').textContent=c.desc;$('#paytable').innerHTML=c.pays.map(p=>`<div><span>${p[0]}</span><b>${p[1]}</b></div>`).join('')+'<div class="handpay-row"><span>HANDPAY</span><b>≥ 10M</b></div>';['#reel1','#reel2','#reel3'].forEach((id,i)=>$(id).textContent=c.symbols[i%c.symbols.length]);$$('[data-cabinet]').forEach(b=>b.classList.toggle('active',b.dataset.cabinet===cabinet))}
$$('[data-cabinet]').forEach(b=>b.onclick=()=>{if(slotBusy)return;cabinet=b.dataset.cabinet;renderCabinet();beep(560,.07,'triangle')});
$$('[data-squick]').forEach(b=>b.onclick=()=>{$('#slotAmount').value=fmt(Number(b.dataset.squick));$('#slotAmount').dispatchEvent(new Event('input'))});$('#slotAmount').oninput=()=>{$('#slotBetDisplay').textContent=$('#slotAmount').value||'—'};
async function spinSlots(forced=null){if(slotBusy)return;const amt=parseAmount($('#slotAmount').value);if(!amt||amt<1)return toast('Enter a chip amount like 100K or 1M.');if(amt>credits)return toast('Not enough chips.');slotBet=amt;slotBusy=true;setCredits(credits-amt);$('#slotSpin').disabled=true;$('#slotStatus').textContent='SPINNING…';const reels=[$('#reel1'),$('#reel2'),$('#reel3')];reels.forEach(r=>r.classList.add('spinning'));const iv=setInterval(()=>{reels.forEach(r=>r.textContent=randSym());beep(160+Math.random()*80,.02,'square',.008)},75);await new Promise(r=>setTimeout(r,1100));clearInterval(iv);const out=forced||[randSym(),randSym(),randSym()];for(let i=0;i<3;i++){await new Promise(r=>setTimeout(r,230));reels[i].classList.remove('spinning');reels[i].textContent=out[i];beep(420+i*120,.09,'triangle',.05)}const mult=slotMult(out),payout=Math.floor(amt*mult);if(payout){setCredits(credits+payout);$('#slotStatus').textContent=`${out.join(' ')} • WIN ${fmt(payout)} • ${mult}×`;winSound();if(payout>=10000000)toast('HANDPAY! '+fmt(payout)+' chips')}else{$('#slotStatus').textContent=`${out.join(' ')} • NO WIN`;loseSound()}$('#slotSpin').disabled=false;slotBusy=false;if(out.filter(x=>x==='★').length>=2)launchBonus();}
$('#slotSpin').onclick=()=>spinSlots();
function launchBonus(forceMult=null){const opts=cabinet==='pulse'?[2,5,10,25,50]:cabinet==='wild'?[5,10,20,30,40]:[3,8,15,30,50];const mult=forceMult||opts[Math.floor(Math.random()*opts.length)];$('#pinballModal').classList.remove('hidden');$('#pinballResult').textContent='BONUS BALL LAUNCHING…';const ball=$('#pinballBall');ball.classList.remove('running');void ball.offsetWidth;ball.classList.add('running');[300,420,520,660,830,980].forEach((f,i)=>setTimeout(()=>beep(f,.08,'triangle',.04),i*350));setTimeout(()=>{const payout=slotBet*mult;setCredits(credits+payout);$('#pinballResult').textContent=`${mult}× MULTIPLIER • +${fmt(payout)} CHIPS`;winSound();if(payout>=10000000)toast('HANDPAY! '+fmt(payout)+' chips')},2850)}
$('#forcePinball').onclick=()=>{slotBet=parseAmount($('#slotAmount').value)||100000;launchBonus()};$('#forceMega').onclick=()=>{slotBet=parseAmount($('#slotAmount').value)||100000;launchBonus(25)};$('#forceHandpay').onclick=()=>{const amt=parseAmount($('#slotAmount').value)||100000;const need=Math.max(10000000,amt*25);setCredits(credits+need);$('#slotStatus').textContent='HANDPAY TEST • +'+fmt(need);toast('HANDPAY! '+fmt(need)+' chips');winSound()};renderCabinet();
