let credits=10000000,sound=true,currentGame=null,bet=100000;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function fmt(n){if(n>=1e9)return +(n/1e9).toFixed(2)+'B';if(n>=1e6)return +(n/1e6).toFixed(2)+'M';if(n>=1e3)return +(n/1e3).toFixed(2)+'K';return Math.floor(n).toLocaleString()}
function amount(s){s=String(s).toUpperCase().replace(/,/g,'').trim();let m=1;if(s.endsWith('K'))m=1e3,s=s.slice(0,-1);if(s.endsWith('M'))m=1e6,s=s.slice(0,-1);if(s.endsWith('B'))m=1e9,s=s.slice(0,-1);return Number(s)*m}
function balance(){ $('#balance').textContent=fmt(credits); $('#gameBalance').textContent=fmt(credits)}
function add(n){credits+=n;balance();beep(500,.05)}
function setBet(v){bet=Math.max(1,amount(v));$('#betInput').value=fmt(bet)}
function beep(f=440,d=.05){if(!sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;o.type='sine';g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.stop(c.currentTime+d)}catch{}}
function win(){beep(880,.1);setTimeout(()=>beep(1200,.13),100)}
function lose(){beep(120,.16)}
function betBox(actionLabel='PLAY'){return `<div class="control-title">CHIP BET</div><div class="bet"><input id="betInput" value="${fmt(bet)}"><button id="half">½</button><button id="double">2×</button></div><div class="quick">${['10K','100K','1M','5M'].map(x=>`<button data-q="${x}">${x}</button>`).join('')}</div><button class="action" id="action">${actionLabel}</button>`}
function bindBet(){const i=$('#betInput');i.onchange=()=>{bet=amount(i.value)||0};$('#half').onclick=()=>setBet(bet/2);$('#double').onclick=()=>setBet(bet*2);$$('[data-q]').forEach(b=>b.onclick=()=>setBet(b.dataset.q))}
function shell(title,stage,controls){$('#gameMount').innerHTML=`<div class="game-panel"><div class="stage ${title.toLowerCase().replaceAll(' ','-')}-stage">${stage}</div><aside class="controls">${controls}</aside></div>`;bindBet();balance()}
function openGame(g){
 currentGame=g;$('.view.active-view')?.classList.remove('active-view');$('#game').classList.add('active-view');$('#crumb').textContent=g.toUpperCase();
 const names={roulette:'Roulette',blackjack:'Blackjack',slots:'Neon Slots',plinko:'Plinko',crash:'Crash',mines:'Mines',dice:'Dice',limbo:'Limbo'};
 $('#gameTitle').textContent=names[g];$('#gameEyebrow').textContent=g==='slots'?'SLOT FLOOR':'ARCADE';
 games[g]();
}
function roulette(){shell('Roulette',`<div class="pointer"></div><div class="roulette-wheel" id="wheel"><span class="roulette-number" id="rnum">?</span><div class="roulette-center">N</div></div><div class="roulette-result" id="rres">PLACE A BET</div>`,`${betBox('SPIN')}<div class="control-title" style="margin-top:18px">BET TYPE</div><div class="bet-types">${['RED','BLACK','GREEN'].map(x=>`<button data-color="${x}">${x}</button>`).join('')}</div><div class="control-title" style="margin-top:15px">NUMBER</div><div class="bet-types" style="grid-template-columns:repeat(5,1fr)">${Array.from({length:37},(_,i)=>`<button data-num="${i}">${i}</button>`).join('')}</div>`);let color=null,num=null;$$('[data-color]').forEach(b=>b.onclick=()=>{color=b.dataset.color;$$('[data-color]').forEach(x=>x.classList.toggle('sel',x===b))});$$('[data-num]').forEach(b=>b.onclick=()=>{num=+b.dataset.num;$$('[data-num]').forEach(x=>x.classList.toggle('sel',x===b))});$('#action').onclick=()=>{bet=amount($('#betInput').value);if(!bet||bet>credits)return;credits-=bet;balance();const n=Math.floor(Math.random()*37),red=[1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36],c=n===0?'GREEN':red.includes(n)?'RED':'BLACK';const angle=-(n*9.729+720+Math.random()*30);$('#wheel').style.transform=`rotate(${angle}deg)`;setTimeout(()=>{$('#rnum').textContent=n;let won=0;if(num===n)won=bet*35;else if(color===c)won=bet*(c==='GREEN'?14:2);if(won){credits+=won;win()}else lose();balance();$('#rres').textContent=`${n} • ${c} • ${won?`WON ${fmt(won)}`:'NO WIN'}`},3250)}}
function blackjack(){let player=[],dealer=[],deck=[];function newDeck(){deck=[];for(const s of ['♠','♥','♦','♣'])for(let n=1;n<=13;n++)deck.push({n,s})}function val(h){let v=h.reduce((a,c)=>a+(c.n>10?10:c.n),0),aces=h.filter(c=>c.n===1).length;while(aces&&v+10<=21)v+=10,aces--;return v}function card(c){return `<div class="playing-card ${c.s==='♥'||c.s==='♦'?'red':''}"><span>${c.n===1?'A':c.n===11?'J':c.n===12?'Q':c.n===13?'K':c.n}${c.s}</span><span>${c.s}</span></div>`}function draw(){return deck.splice(Math.floor(Math.random()*deck.length),1)[0]}function render(){shell('Blackjack',`<div class="table"><div class="hand-label">DEALER • <span class="score">${val(dealer)}</span></div><div class="hand">${dealer.map(card).join('')}</div><div class="hand-label">PLAYER • <span class="score">${val(player)}</span></div><div class="hand">${player.map(card).join('')}</div></div>`,`${betBox('DEAL')}<div style="display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:7px"><button class="ghost-action" id="hit">HIT</button><button class="ghost-action" id="stand">STAND</button><button class="ghost-action" id="dbl">DOUBLE</button><button class="ghost-action" id="split">SPLIT</button></div>`);bindBet();$('#action').onclick=deal;$('#hit').onclick=hit;$('#stand').onclick=stand;$('#dbl').onclick=()=>{if(player.length===2&&credits>=bet){credits-=bet;bet*=2;balance();hit();stand()}};$('#split').onclick=()=>{if(player.length===2&&player[0].n===player[1].n&&credits>=bet){credits-=bet;balance();$('#rres')?.remove();toast('Split demo: hands can be added in the next table expansion.')}}}function deal(){bet=amount($('#betInput').value);if(!bet||bet>credits)return;credits-=bet;newDeck();player=[draw(),draw()];dealer=[draw(),draw()];render();if(val(player)===21)stand()}function hit(){player.push(draw());render();if(val(player)>21)finish(false)}function stand(){while(val(dealer)<17)dealer.push(draw());render();finish(val(player)<=21&&(val(dealer)>21||val(player)>val(dealer)))}function finish(winIt){setTimeout(()=>{if(winIt){credits+=bet*2;win()}else lose();balance()},450)}newDeck();render()}
function slots(){shell('Neon Slots',`<div class="reels"><div class="reel" id="a">7</div><div class="reel" id="b">★</div><div class="reel" id="c">7</div></div>`,`${betBox('SPIN')}<div class="control-title" style="margin-top:18px">CABINET</div><div class="quick"><button data-cab="classic">CLASSIC</button><button data-cab="wild">WILD</button><button data-cab="crystal">CRYSTAL</button></div><div class="control-title" style="margin-top:12px">BONUS MAP</div><div style="font-size:11px;line-height:2;color:#8b9d91">🍒🍒🍒 = 2×<br>★ ★ ★ = 5×<br>7 7 7 = 20×<br>💎💎💎 = 50×</div>`);let syms=['7','★','◆','●','BAR','🍒','💎'];$('#action').onclick=()=>{bet=amount($('#betInput').value);if(!bet||bet>credits)return;credits-=bet;balance();$$('.reel').forEach(x=>x.classList.add('spin'));let out=[];setTimeout(()=>{for(let i=0;i<3;i++)out.push(syms[Math.floor(Math.random()*syms.length)]);['a','b','c'].forEach((id,i)=>{$('#'+id).textContent=out[i];$('#'+id).classList.remove('spin')});let mult=out.every(x=>x==='7')?20:out.every(x=>x==='★')?5:out.every(x=>x==='💎')?50:out[0]==='🍒'&&out[1]==='🍒'&&out[2]==='🍒'?2:0;if(mult){credits+=bet*mult;win()}else lose();balance()},900)}}
function plinko(){shell('Plinko',`<div class="plinko-board" id="pb"><div id="pegs"></div><div class="slotrow">${[.2,.5,1,2,5,2,1,.5,.2].map(x=>`<span>${x}×</span>`).join('')}</div></div>`,`${betBox('DROP CHIP')}<div class="control-title" style="margin-top:18px">RISK</div><div class="quick"><button>LOW</button><button>MEDIUM</button><button>HIGH</button></div>`);let p=$('#pegs');for(let r=0;r<10;r++)for(let c=0;c<r+3;c++){let e=document.createElement('i');e.className='peg';e.style.left=(30+c*4.5)+'%';e.style.top=(8+r*8)+'%';p.appendChild(e)}$('#action').onclick=()=>{bet=amount($('#betInput').value);if(!bet||bet>credits)return;credits-=bet;balance();let b=document.createElement('i');b.className='ball';b.style.left='50%';b.style.top='3%';$('#pb').appendChild(b);let x=50;let y=4;let t=setInterval(()=>{x+=(Math.random()>.5?4:-4);y+=7;b.style.left=x+'%';b.style.top=y+'%';if(y>78){clearInterval(t);let mult=[.2,.5,1,2,5,2,1,.5,.2][Math.floor(Math.random()*9)];let winAmt=Math.floor(bet*mult);credits+=winAmt;balance();if(winAmt>=bet)win();else lose();setTimeout(()=>b.remove(),300)}},120)}}
function crash(){shell('Crash',`<div class="crash-stage"><div class="crash-number" id="cr">1.00×</div><div class="crash-line"><svg viewBox="0 0 600 240"><polyline id="crLine" points="0,230 80,220 150,225 240,165 330,185 420,90 520,120 600,15"/></svg></div></div>`,`${betBox('START ROUND')}<div id="cash" style="margin-top:15px;color:#7cff95;font-weight:1000;text-align:center">CASH OUT AVAILABLE AFTER START</div>`);$('#action').onclick=()=>{bet=amount($('#betInput').value);if(!bet||bet>credits)return;credits-=bet;balance();let m=1+Math.random()*8,cur=1;$('#action').disabled=true;let t=setInterval(()=>{cur+=.04+cur*.008;$('#cr').textContent=cur.toFixed(2)+'×';if(cur>=m){clearInterval(t);lose();$('#cash').textContent=`CRASHED AT ${m.toFixed(2)}×`;$('#action').disabled=false}else $('#cash').innerHTML=`<button class="action" id="cashout">CASH OUT ${cur.toFixed(2)}×</button>`},80);setTimeout(()=>{const b=$('#cashout');if(b)b.onclick=()=>{clearInterval(t);credits+=Math.floor(bet*cur);balance();win();$('#cash').textContent=`PAID ${fmt(Math.floor(bet*cur))}`}},100)}}
function mines(){shell('Mines',`<div style="display:grid;place-items:center"><div class="mine-grid" id="mg">${Array.from({length:25},(_,i)=>`<button data-cell="${i}">?</button>`).join('')}</div></div>`,`${betBox('START')}<div style="font-size:10px;color:#718276;line-height:1.5;margin-top:12px">Reveal safe tiles. A mine ends the round. Fictional chips only.</div>`);let started=false,mineset=[];$('#action').onclick=()=>{bet=amount($('#betInput').value);if(!bet||bet>credits)return;credits-=bet;balance();mineset=[];while(mineset.length<5){let n=Math.floor(Math.random()*25);if(!mineset.includes(n))mineset.push(n)}started=true;$$('[data-cell]').forEach(x=>x.textContent='?')};$$('[data-cell]').forEach(b=>b.onclick=()=>{if(!started)return;let n=+b.dataset.cell;if(mineset.includes(n)){b.classList.add('bomb');b.textContent='✦';lose();started=false}else{b.classList.add('safe');b.textContent='◆';credits+=Math.floor(bet*.35);balance();win()}})}
function dice(){shell('Dice',`<div class="dice-stage"><div class="big-dice" id="dv">—</div><div style="color:#66776b;font-size:10px">ROLL 1–100</div></div>`,`${betBox('ROLL')}<div class="bet-types"><button>LOW &lt; 50</button><button>HIGH &gt; 50</button><button>EXACT</button></div>`);$('#action').onclick=()=>{bet=amount($('#betInput').value);if(!bet||bet>credits)return;credits-=bet;let n=Math.floor(Math.random()*100)+1;$('#dv').textContent=n;let w=n>50;let p=w?Math.floor(bet*1.9):0;if(p)credits+=p;balance();w?win():lose()}}
function limbo(){shell('Limbo',`<div class="limbo-stage"><div class="limbo-mult" id="lm">1.00×</div><div style="color:#756d80;font-size:10px">TARGET MULTIPLIER</div></div>`,`${betBox('ROLL')}<div class="control-title" style="margin-top:18px">TARGET</div><div class="bet"><input id="target" value="2.00"></div>`);$('#action').onclick=()=>{bet=amount($('#betInput').value);let target=Math.max(1.01,Number($('#target').value));if(!bet||bet>credits)return;credits-=bet;let m=1+Math.random()*9;$('#lm').textContent=m.toFixed(2)+'×';if(m>=target){credits+=Math.floor(bet*target);win()}else lose();balance()}}
const games={roulette,blackjack,slots,plinko,crash,mines,dice,limbo};
$$('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));
$$('[data-view]').forEach(b=>b.onclick=()=>{$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+b.dataset.view).classList.add('active-view');$('#crumb').textContent=b.dataset.view.toUpperCase()});
$$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.view==='home'){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#home').classList.add('active-view')}});
$('#plus').onclick=()=>add(1000000);$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊 Sound':'🔇 Sound'};
$('#devBtn').onclick=()=>$('#devModal').classList.add('open');$('#closeDev').onclick=()=>$('#devModal').classList.remove('open');$('#devModal').onclick=e=>{if(e.target.id==='devModal')e.target.classList.remove('open')};
$$('[data-add]').forEach(b=>b.onclick=()=>add(amount(b.dataset.add)));$('#reset').onclick=()=>{credits=10000000;balance()};
$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
balance();
